// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/search/search.proto

package search

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchComicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phrase        string                 `protobuf:"bytes,1,opt,name=phrase,proto3" json:"phrase,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchComicsRequest) Reset() {
	*x = SearchComicsRequest{}
	mi := &file_proto_search_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchComicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchComicsRequest) ProtoMessage() {}

func (x *SearchComicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchComicsRequest.ProtoReflect.Descriptor instead.
func (*SearchComicsRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchComicsRequest) GetPhrase() string {
	if x != nil {
		return x.Phrase
	}
	return ""
}

func (x *SearchComicsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchComic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchComic) Reset() {
	*x = SearchComic{}
	mi := &file_proto_search_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchComic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchComic) ProtoMessage() {}

func (x *SearchComic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchComic.ProtoReflect.Descriptor instead.
func (*SearchComic) Descriptor() ([]byte, []int) {
	return file_proto_search_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchComic) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchComic) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SearchComicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comics        []*SearchComic         `protobuf:"bytes,1,rep,name=comics,proto3" json:"comics,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchComicsResponse) Reset() {
	*x = SearchComicsResponse{}
	mi := &file_proto_search_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchComicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchComicsResponse) ProtoMessage() {}

func (x *SearchComicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchComicsResponse.ProtoReflect.Descriptor instead.
func (*SearchComicsResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchComicsResponse) GetComics() []*SearchComic {
	if x != nil {
		return x.Comics
	}
	return nil
}

func (x *SearchComicsResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_search_search_proto protoreflect.FileDescriptor

const file_proto_search_search_proto_rawDesc = "" +
	"\n" +
	"\x19proto/search/search.proto\x12\x06search\x1a\x1bgoogle/protobuf/empty.proto\"C\n" +
	"\x13SearchComicsRequest\x12\x16\n" +
	"\x06phrase\x18\x01 \x01(\tR\x06phrase\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"/\n" +
	"\vSearchComic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"Y\n" +
	"\x14SearchComicsResponse\x12+\n" +
	"\x06comics\x18\x01 \x03(\v2\x13.search.SearchComicR\x06comics\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total2\x90\x01\n" +
	"\rSearchService\x12E\n" +
	"\x06Search\x12\x1b.search.SearchComicsRequest\x1a\x1c.search.SearchComicsResponse\"\x00\x128\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00B\x1fZ\x1dyadro.com/course/proto/searchb\x06proto3"

var (
	file_proto_search_search_proto_rawDescOnce sync.Once
	file_proto_search_search_proto_rawDescData []byte
)

func file_proto_search_search_proto_rawDescGZIP() []byte {
	file_proto_search_search_proto_rawDescOnce.Do(func() {
		file_proto_search_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_search_search_proto_rawDesc), len(file_proto_search_search_proto_rawDesc)))
	})
	return file_proto_search_search_proto_rawDescData
}

var file_proto_search_search_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_search_search_proto_goTypes = []any{
	(*SearchComicsRequest)(nil),  // 0: search.SearchComicsRequest
	(*SearchComic)(nil),          // 1: search.SearchComic
	(*SearchComicsResponse)(nil), // 2: search.SearchComicsResponse
	(*emptypb.Empty)(nil),        // 3: google.protobuf.Empty
}
var file_proto_search_search_proto_depIdxs = []int32{
	1, // 0: search.SearchComicsResponse.comics:type_name -> search.SearchComic
	0, // 1: search.SearchService.Search:input_type -> search.SearchComicsRequest
	3, // 2: search.SearchService.Ping:input_type -> google.protobuf.Empty
	2, // 3: search.SearchService.Search:output_type -> search.SearchComicsResponse
	3, // 4: search.SearchService.Ping:output_type -> google.protobuf.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_search_search_proto_init() }
func file_proto_search_search_proto_init() {
	if File_proto_search_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_search_search_proto_rawDesc), len(file_proto_search_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_search_search_proto_goTypes,
		DependencyIndexes: file_proto_search_search_proto_depIdxs,
		MessageInfos:      file_proto_search_search_proto_msgTypes,
	}.Build()
	File_proto_search_search_proto = out.File
	file_proto_search_search_proto_goTypes = nil
	file_proto_search_search_proto_depIdxs = nil
}
